
public enum Species {

	BALSAM_FIR, WHITE_SPRUCE, BLACK_SPRUCE, RED_SPRUCE, EASTERN_WHITE_CEDAR, EASTERN_LARCH, WHITE_PINE, RED_PINE, JACK_PINE, EASTERN_HEMLOCK,
	RED_MAPLE, SUGAR_MAPLE, YELLOW_BIRCH, WHITE_BIRCH, GREY_BIRCH, LARGE_TOOTHED_ASPEN, TREMBLING_ASPEN, IRON_WOOD, BLACK_CHERRY, AMERICAN_BEECH,
	RED_OAK, WHITE_ASH, GENERIC_HARD_WOOD, GENERIC_SOFT_WOOD;
}
